[project]
name = "sieve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cython>=3.2.3",
    "numpy>=2.3.4",
    "setuptools>=80.9.0",
]
